# Generated by Django 6.0.3 on 2026-03-21 08:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Menu Name')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='About menu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='MenuItem Image')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Base Price')),
                ('is_veg', models.BooleanField(default=False, verbose_name='Vegetarian')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='BestSeller')),
                ('is_available', models.BooleanField(default=True, verbose_name='Availability')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.category', verbose_name='Category')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemVariants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Half/Full/Small/Regular/Large', max_length=50, verbose_name='Variant Name')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Variant Price')),
                ('is_available', models.BooleanField(default=True, verbose_name='Availability')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='restaurants.menuitem', verbose_name='Menu Item')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='RestaurantId')),
                ('name', models.CharField(max_length=200, verbose_name='Restaurant Name')),
                ('description', models.TextField(max_length=600, verbose_name='Description')),
                ('cuisine_type', models.CharField(choices=[('NORTH_INDIAN', 'North Indian'), ('SOUTH_INDIAN', 'South Indian'), ('CHINESE', 'Chinese'), ('ITALIAN', 'Italian'), ('STREET_FOOD', 'Street Food & Chaat'), ('BIRYANI', 'Biryani'), ('PIZZA', 'Pizza'), ('BURGER', 'Burgers & Fast Food'), ('DESSERTS', 'Desserts & Mithai'), ('BEVERAGES', 'Beverages'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Cuisine Type')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('city', models.CharField(max_length=50, verbose_name='')),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a valid 6-digit pin code')], verbose_name='Pin Code')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit phone number')], verbose_name='Phone')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('is_open', models.BooleanField(default=True, verbose_name='Open/Closed')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=8, verbose_name='Minimum Order Amount')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Delivery Fee')),
                ('avg_delivery_time', models.PositiveIntegerField(default=30, help_text='delivery time in minutes', verbose_name='Delivery Time in minutes')),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3, verbose_name='Average Rating')),
                ('total_ratings', models.PositiveIntegerField(default=0, verbose_name='Total Ratings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'RESTAURANT_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='Restaurant Owner')),
            ],
            options={
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-average_rating', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurants', verbose_name='Restaurants'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['name'], name='restaurants_name_e810f2_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemvariants',
            index=models.Index(fields=['menu_item', 'name'], name='restaurants_menu_it_b98e05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemvariants',
            unique_together={('menu_item', 'name')},
        ),
        migrations.AddIndex(
            model_name='restaurants',
            index=models.Index(fields=['name'], name='restaurants_name_e91966_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurants',
            index=models.Index(fields=['cuisine_type'], name='restaurants_cuisine_d8be20_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurants',
            index=models.Index(fields=['city'], name='restaurants_city_ac1832_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurants',
            index=models.Index(fields=['is_active', 'is_open'], name='restaurants_is_acti_94c7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['restaurant', 'name'], name='restaurants_restaur_803069_idx'),
        ),
    ]
