# Generated by Django 6.0.3 on 2026-03-19 20:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='userId')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=100, verbose_name='full name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='phone number')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('RESTAURANT_OWNER', 'Restaurant Owner'), ('DELIVERY_AGENT', 'Delivery Agent')], default='CUSTOMER', max_length=20, verbose_name='user role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Phone Verified')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/customers/', verbose_name='Profile Picture')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Vegetarian')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total Orders')),
                ('loyalty_points', models.PositiveIntegerField(default=0, verbose_name='Loyalty Points')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('formatted_address', models.TextField(blank=True, verbose_name='Google Formatted Address')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('label', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('OTHER', 'Other')], default='HOME', max_length=10, verbose_name='Address Type')),
                ('flat_number', models.CharField(max_length=100, verbose_name='House/Flat/Floor No.')),
                ('address_line', models.CharField(max_length=250, verbose_name='Apartment/Road/Area')),
                ('landmark', models.CharField(blank=True, max_length=250, verbose_name='Landmark')),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a valid 6-digit pincode')], verbose_name='Pin Code')),
                ('receiver_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number')], verbose_name='Receiver Phone')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.customerprofile')),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Agent Profile Picture')),
                ('vehicle_type', models.CharField(choices=[('BICYCLE', 'Bicycle'), ('SCOOTER', 'Scooter'), ('BIKE', 'Bike')], default='BIKE', max_length=10, verbose_name='Vehicle Type')),
                ('vehicle_number', models.CharField(max_length=15, verbose_name='Vehicle Number')),
                ('driving_license', models.CharField(max_length=20, verbose_name='Driving License')),
                ('status', models.CharField(choices=[('OFFLINE', 'Offline'), ('AVAILABLE', 'Available'), ('ON_DELIVERY', 'On Delivery')], default='AVAILABLE', max_length=15, verbose_name='Agent Status')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Current Latitude')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Current longitude')),
                ('last_location_update', models.DateTimeField(blank=True, null=True, verbose_name='Last Location Update')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='Total Deliveries')),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3, verbose_name='Average Rating')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Verification Token')),
                ('expires_at', models.DateTimeField(verbose_name='Expiry Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verification_tokens',
            },
        ),
        migrations.CreateModel(
            name='RestaurantOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/owners/', verbose_name='Profile Picture')),
                ('pan_number', models.CharField(blank=True, max_length=50, verbose_name='Pan Number')),
                ('gst_number', models.CharField(blank=True, max_length=50, verbose_name='Gst number')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verification Status')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
