# Generated by Django 6.0.3 on 2026-03-20 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='formatted_address',
            field=models.TextField(blank=True, verbose_name='Map Formatted Address'),
        ),
        migrations.AlterField(
            model_name='restaurantownerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
